name: Docker Android CI

on:
  workflow_dispatch:

jobs:

  # Builds all Android API images with API level 33 and below.
  build-apis:
    strategy:
      matrix:
        version: [33, 32, 31, 30, 29, 28]
        image: [
          { name: 'google_apis', suffix: '' },
          { name: 'google_apis_playstore', suffix: '-playstore' }
        ]
        gpu: [
          { file: 'Dockerfile', suffix: '' },
          { file: 'Dockerfile.gpu', suffix: '-cuda' }
        ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image api-${{ matrix.version }}${{ matrix.image.suffix }}
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ matrix.gpu.file }}
          tags: ghcr.io/noahsurprenant/android-emulator:api-${{ matrix.version }}${{ matrix.image.suffix }}${{ matrix.gpu.suffix }}
          build-args: |
            API_LEVEL=${{ matrix.version }}
            IMG_TYPE=${{ matrix.image.name }}

  # Builds a minimal image without any Android SDK images.
  build-minimal:
    strategy:
      matrix:
        gpu: [
          { file: 'Dockerfile', suffix: '' },
          { file: 'Dockerfile.gpu', suffix: '-cuda' }
        ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build minimal Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ matrix.gpu.file }}
          tags: ghcr.io/noahsurprenant/android-emulator:minimal${{ matrix.gpu.suffix }}
          build-args: INSTALL_ANDROID_SDK=0
